"""Add worker_id to sales_leads

Revision ID: 8df86f9661b9
Revises: 
Create Date: 2024-11-16 21:49:59.456356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8df86f9661b9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lead_status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('lead_source', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('potential_value', sa.Float(), nullable=True))
        batch_op.create_foreign_key(None, 'workers', ['worker_id'], ['id'])
        batch_op.drop_column('status')

    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('assigned_to', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('ticket_subject', sa.String(length=200), nullable=False))
        batch_op.add_column(sa.Column('ticket_description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('ticket_status', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('description')
        batch_op.drop_column('status')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True))
        batch_op.drop_column('updated_at')
        batch_op.drop_column('ticket_status')
        batch_op.drop_column('ticket_description')
        batch_op.drop_column('ticket_subject')
        batch_op.drop_column('assigned_to')
        batch_op.drop_column('created_by')

    with op.batch_alter_table('sales_leads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('potential_value')
        batch_op.drop_column('lead_source')
        batch_op.drop_column('lead_status')
        batch_op.drop_column('worker_id')

    # ### end Alembic commands ###
