"""Update assigned_to to reference Worker

Revision ID: d610b6c25bd8
Revises: 8df86f9661b9
Create Date: 2024-11-16 22:53:20.857555

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd610b6c25bd8'
down_revision = '8df86f9661b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        # Using 'USING' to cast assigned_to column to integer
        batch_op.alter_column('assigned_to',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=True,
               postgresql_using='assigned_to::integer')  # Explicitly cast the value
        batch_op.create_foreign_key(None, 'workers', ['assigned_to'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('support_tickets', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('assigned_to',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    # ### end Alembic commands ###
