"""Fix analytics_id auto-increment

Revision ID: df34000fdf80
Revises: 5318a6ff3e86
Create Date: 2024-11-17 16:41:17.996360

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'df34000fdf80'
down_revision = '5318a6ff3e86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('worker_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('period_start_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('period_end_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('metric_value',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('analytics', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
        batch_op.alter_column('metric_value',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
        batch_op.alter_column('period_end_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('period_start_date',
               existing_type=sa.DATE(),
               nullable=True)
        batch_op.alter_column('worker_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
